# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  vault_adress: <%= ENV["VAULT_ADDR"] %>
  vault_token: <%= ENV["VAULT_TOKEN"] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62363a59925a0331f946bf3271c6652384c8c211b05a82075e402cc2a514b62414df188585313ecd911b1f3cd0c9847fa2e1bf8ff0fb35a042d0d9c8a21988c9
  devise_secret_key: 92e7de6877d36ea42ce364e1c2b93171c0d10869d31b998c0cbc61285784697c0077686203ff85f53496809975f4731fa4a6458ad39523f0be114a7812777a10

  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_phone_number: '+15005550006'

  storage_provider: <%= ENV.fetch('STORAGE_PROVIDER', 'local') %>
  storage_bucket_name: <%= ENV['STORAGE_BUCKET_NAME'] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY'] %>
  storage_secret_key: <%= ENV['STORAGE_SECRET_KEY'] %>
  storage_region: <%= ENV['STORAGE_REGION'] %>

  jwt_shared_secret_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMlNKS0FJYmxxajhCZmlhRlloTnhYclQzdmQ4Y3NSd1VYUy9ZenJRRWpEMXRJUU16ClNtaVBabUNhc2xUT3hvcW9MU3I3bEIyMWpwYm5iNW5HYXNPcTMrRUtVZ3ppS0Q1STk0WS9DeXpaR2prbUZGNy8KZFFoV1RwYjU5ODFhVW1ST1FkVDVUcnlDZXlra0VDdkM2QlI3R2ZMNk1mQlJGb2EzbkVBUlRTNExKRkRaSUJjRwpmZk4zc2VKQkNBVkdUd081aHdCRXMzWmxyWkEzdWtXcGE2Rnc3RmR4VkR3TFZMcnk3TGE0NVl2MytUOTRRM3BDCnRWZEc5eUJTSGpZU3VjeDlFdVF0S2RzOFh3bWRMRStYV3d5emt1QytyUERPcnhic0xlZ0cxMWp3VVhLT0FuZFYKRkhidzV6VkEyMzV2bzNoVzZXQzhCd1RxQ2l4QlYvR1B1Sll4SXdJREFRQUJBb0lCQUVTNlhjSWM4TVVhZkZaNQp5dTVvU1JJNUpkR3J0V0U2Q2hnVTlRTTRaOWdiK1ZiaHRISnc5akxwa1EyeFdtSHRzWjNhWlJkVThBcmFLUmRpCkRUUHVDMEFoOHlwVmVhQlRWclZDZ09JQXFCZHN6MmpUU1BpNlV0YzlZcEhWSmltK0ppY2dTbWxwc2NOYUdsZ2sKQWVXRDFoTTRuWWtCRUNtWktyVUNjbmVEZzNOU3JpM004b3dkN2QyM2RqRUhpRnBKM3pnd014M1dRSG5ubmNSWAo1VTZNbkxIN2Nqb3lUVjFhMnZHaVFNQ0JIZXRra3IrSnVVek16SHc4MmU5ZWhuWW93cTJ1RXAwZzdna0ZFTXlPCnBtRkl4TGc5MDBzUG9GbldXSjFQeEIvQyt2U3gzZTM4bzlxdG15YXFUUGRRdDZjZ1NTd0MrSlhId0NIVThQTzMKa1gyVnNVRUNnWUVBL3ozTzNFbnl2eEp4UHZ5NEhVNVpNU3dpRVkxRHJkY2NoWkZFUmlVL0hiYWZnZjIvd0VCZgpFcFp5ZE91bDRXNENjSUZoOVY2ZnI1WVoySHd2aEkxMHhCeGlqSkhQZGltV0E4UGZvMXA1SzRabmxGUG5seG52Ck9XeUczK0xUb0NmOHlyR3RFLzl4cFRHaWhSQUsweHlUeEtUWUh0ZThsd3RrbmJNZ3hJS2pUdThDZ1lFQTJjZDgKK3MwR09iYVRuUEQ0STR6VTNqanB0Y29xMXpzbkZtc1ZOaXo4eXhVSnVsbXdDQ1dJNUcyWjFTdUpHem9uQ1h3Swp4Q0ErUFZPdVBFVnA1dDhNZTJCVk1rYW1vMjdHSE9TTFhQTkNOR29KRVBiRUtpTTlZMVZkK2FVbnI2S2pQbTR0CjJPN2sxMXNTVjl6Yk1Hd2pkUDNMTXI5U1VramNpUHF6dENUSHdRMENnWUFCcHJ5MzRDS1o2ZHloczdEZFA2eUUKRE8wTGdBWjRFWFExeVFMUUVWMmZLNWRNbC8rdGxyMEd1Y0p6enpKN2l1S3BKNjBpa1VJbk9LbGlKU3VKaUFEQgpaQTJmS3pKVWFXQjNGY1ZVb1RrM2R0OGtyb1pKQy9ub1BUT0NMMDEvTThNRzdLOVorY1VhZEgvQXJLSGxTOElJCis2Z0tTd3NGVHlXUGY2RXVwRW02TVFLQmdDVFJuVWVwc2d1LzJtVUdPRzJLT2RMNFBFc0h5d1pvY2N0UWYxMlIKYll2SUdzVHV0TndydkdFaVJvZkx2SHBsOG9PZi9SSDdnWXBNdzRCZEcvSjBjMS9JZ1o3bVl2WHVuSC8yQTduTApScjRsenpLWEJjTTZBZjd4UjlvVkdnaVBycG0zZHZqZUtzSmVHMVBQZXg5TXFSSDJkb3cxM0cwYzlHd1VOcDJXCk9rOWhBb0dCQVAwS1BiSGlGeUVYZFErQU5xVmFIZ3JGa0lVMVVqcGpGOFl2NjBPNWJGVHpsT3ZYVi9vckNhcmwKSHlXWkF2a3BnRVl0akFxdTd3Z2hTSTI1MkF2SlBOZzBXdlBmdVlwUnRxNlVEVTlHTDhsZ29hQUFhakl2V09xUQp6VC9Kd1Jnd1UxYktLSzBzS3JJTVJTaXp5MEg3NiszdUZNUGMyVGhISVBLVjJiK2h4MUVzCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

test:
  secret_key_base: f35908345f0ee30027ecd785cf207a2311a70ee31d5a9e2153c4fd07dae216fae9cad4d47b5c87b764f28d6519e320ddae948038ca184ced5a457b03b94e859d
  devise_secret_key: d419eb32eb538bfcdbdeee9f71d1b70889950c870652965e26d324e78a5c983d814e7873b55693e0e90701db6e3d3fad956e63b823ce993685156141afbe4c66

  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_phone_number: '+15005550006'

  storage_provider: <%= ENV.fetch('STORAGE_PROVIDER', 'local') %>
  storage_bucket_name: <%= ENV['STORAGE_BUCKET_NAME'] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY'] %>
  storage_secret_key: <%= ENV['STORAGE_SECRET_KEY'] %>
  storage_region: <%= ENV['STORAGE_REGION'] %>

  jwt_shared_secret_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdU4wbkhOaFUycm5lNXhNUkxCbVh2bDRBcWtBcU1LT0JBVGk4NDRpeU1HdU5uT0EyCmRQRHRmcTJYeENYY0FvQW4yc0dhdFRuWnhnSlpkd1Y3Q050VzdKRzg4bVExWGFBTFdlVEd6VGkwTVZsMHNHUVYKT1MycWY3a21mWlFKaDhDRU1ZNS9oQ1JKQzBxZzZMN09LcmpuT2FaZ3BGWXVoNUdxQ05ONkI1V2Nmd3g5TksrWApWK3h5eHJEb2l4eG15ZEhBMkViT1MrWXh2S1JlVXJXS3k1TElSVWlpQzA0TVB2WXRrcW5CY3dyek5mY21UTU1MCnB0MjhiWVl5elQ0S09jcDFvVTFnUnNqa0kwWmJNYUdFRlNjWk1EU2l5NGsrSnZ6dmJubXphcExDSTFPcHJWMmYKZW1TRzYydi9DaWVaOU5Hbm82YUh3bGNXR0lVTmN6TXgvVUp5dlFJREFRQUJBb0lCQVFDMDlRYU1YZGJ5SkcvbAprZXlGVnFnTFdNa2QzcUZ0Nng4a3F2MTdYUnZQK2ZndFQreittN2hmQUY1SFN5Z0o2cGtZc2R0VytzSUo2ZExaCmh5dmdoNVNYRGpIK3M4anBWUGpIamdKc2NNMHlZWGF3RThnU3FIajFmYkFIelJsbklUUkZyazkwY25CdDlTZDkKclFqekdQeCttamFQcHl6MDE4bXh5aER4eTZuZFVoaTRNMVNVRUVmWGdRMitoWHM4WS82RzVoZzZwMnFJWnhCUgp4d2oxeEIvMHZnUENQVmRMdUIzZ0poR1ZoellDVUV0QkdNTEViZDhnQU0xWGNDSnRvaUpHdldGY2xBT056L3pqCjYvYStHQmxNZVNOdEJVMHNtVHVLL1NvTFMxSVhpc2h3cjVJMmpta1BiaSt3M0ttSVVNZW1QMEQxS0w0QVc5ZHUKSDVvWmpCTUJBb0dCQU80cU9IZHhycVlsaGVZRE9CNkNKVUlnbDZIYTZ2d01PbU5vREdUL1JMUnBBeFRlcWJxUwo2VnJHdHNGSU9WWTZLTzBpMm9SczNNdW9OZ0o4SGVWQ1dhNS9zbVhYeE0rQTZRR1A1ZEhuM3YrV25vVDU2RVRPCkh3a2I1d2FhbHpaMS8wUm9GbGR5a2QwN0hweGdxVjJTRER1SUUycGhaeGxJTlQveklSOFJjYWlwQW9HQkFNYTEKSGFkcmdXWXZpOWpPd0NNYzNkYVBzbDZYV3dhQmd0QjBRYXVqRWhHMzBvYlNDV0tHR0RiSU92TnFSK2o5TDJEWApCR0h6U2dBeTJHdDRzSS9ialhJMW40c0NyUDJzYUJrSWx1aWhuak95R0MwTjFieGxjNGNibU1DaXNWVVRScXNUCk1IblcrZmFKN3JPb1U1TmIvbmlQNFBzamFhdC9tWnkraEtZZWRHSDFBb0dBY0pnSFAvaS9yNDZYd2NrTjArYUYKUk1EeHpyUVhXWGRTZDBKdWNhVDR6eTNDSmpDcUh5bHJKdDVBOGhsNStkamZGbFRlNTdJcnBDQnZBRGU3VG5KUwp3WnRmTktTUVIrVlN3c2xMeGpPUGlsZWpzNHdPRWRFOGZPcnpDbjAxTmFzTk5rTGJKUlpsL1NnQTdiOEk4dEtqCjg5VCtFTkhoa3VNL1FXOW8zaTQ2QkprQ2dZRUF4UmRvTG1Obm1kK1hLcGtINHN3RERZckNOU2lUVk1TbzUvSW8KSVFKQ0xlalNuSDlBWjhUeHg0U2JWRTBhdm5KQ3lCNzliZHBPa0J2ZXBkcXo1anl5ODVGVWlpRkJUT3Z3NU1PcwpTMW5pL1F1dEJ5TXQyUXdYcHU4c2VBWG5OcWREOVBPM3BXSWgxUFBERzlmZDdjL1ZlK2ZhRTc5d1ZIYmYrcVRPCkZhY25jUEVDZ1lFQTNLTjNxZ3E5Y3ZqM3E5cTJUekt6MFpLYVVkbm1yY0txbVBzdU1VeXpoUlpHa0RyYmlnZG0KMU1jSU90VVlOZy81aWVUYWc4bEpXcW9yL1RCRjhaNmRTV0VDd3hURy9LakU5Vk1BcS94QVU3YUZ0TUFOT1h0TApaVFVkNUl3Z2N1STcweCtYQVRGZ1JldGFrcDVHSCtRYmhoYTNOUnl2UEJGcUd2NS8yNnlHV1VZPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_phone_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>

  storage_provider: <%= ENV.fetch('STORAGE_PROVIDER', 'local') %>
  storage_bucket_name: <%= ENV['STORAGE_BUCKET_NAME'] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY'] %>
  storage_secret_key: <%= ENV['STORAGE_SECRET_KEY'] %>
  storage_region: <%= ENV['STORAGE_REGION'] %>

  jwt_shared_secret_key: <%= ENV["JWT_SHARED_SECRET_KEY"] %>
